// This file is generated by "./lib/proto/generate"

package proto

/*

DOMStorage

Query and modify DOM storage.

*/

// DOMStorageStorageID DOM Storage identifier.
type DOMStorageStorageID struct {

	// SecurityOrigin Security origin for the storage.
	SecurityOrigin string `json:"securityOrigin"`

	// IsLocalStorage Whether the storage is local storage (not session storage).
	IsLocalStorage bool `json:"isLocalStorage"`
}

// DOMStorageItem DOM Storage item.
type DOMStorageItem []string

// DOMStorageClear ...
type DOMStorageClear struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`
}

// ProtoReq of the command
func (m DOMStorageClear) ProtoReq() string { return "DOMStorage.clear" }

// Call of the command, sessionID is optional.
func (m DOMStorageClear) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// DOMStorageDisable Disables storage tracking, prevents storage events from being sent to the client.
type DOMStorageDisable struct {
}

// ProtoReq of the command
func (m DOMStorageDisable) ProtoReq() string { return "DOMStorage.disable" }

// Call of the command, sessionID is optional.
func (m DOMStorageDisable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// DOMStorageEnable Enables storage tracking, storage events will now be delivered to the client.
type DOMStorageEnable struct {
}

// ProtoReq of the command
func (m DOMStorageEnable) ProtoReq() string { return "DOMStorage.enable" }

// Call of the command, sessionID is optional.
func (m DOMStorageEnable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// DOMStorageGetDOMStorageItems ...
type DOMStorageGetDOMStorageItems struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`
}

// ProtoReq of the command
func (m DOMStorageGetDOMStorageItems) ProtoReq() string { return "DOMStorage.getDOMStorageItems" }

// Call of the command, sessionID is optional.
func (m DOMStorageGetDOMStorageItems) Call(c Client) (*DOMStorageGetDOMStorageItemsResult, error) {
	var res DOMStorageGetDOMStorageItemsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// DOMStorageGetDOMStorageItemsResult ...
type DOMStorageGetDOMStorageItemsResult struct {

	// Entries ...
	Entries []DOMStorageItem `json:"entries"`
}

// DOMStorageRemoveDOMStorageItem ...
type DOMStorageRemoveDOMStorageItem struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`

	// Key ...
	Key string `json:"key"`
}

// ProtoReq of the command
func (m DOMStorageRemoveDOMStorageItem) ProtoReq() string { return "DOMStorage.removeDOMStorageItem" }

// Call of the command, sessionID is optional.
func (m DOMStorageRemoveDOMStorageItem) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// DOMStorageSetDOMStorageItem ...
type DOMStorageSetDOMStorageItem struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`

	// Key ...
	Key string `json:"key"`

	// Value ...
	Value string `json:"value"`
}

// ProtoReq of the command
func (m DOMStorageSetDOMStorageItem) ProtoReq() string { return "DOMStorage.setDOMStorageItem" }

// Call of the command, sessionID is optional.
func (m DOMStorageSetDOMStorageItem) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// DOMStorageDomStorageItemAdded ...
type DOMStorageDomStorageItemAdded struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`

	// Key ...
	Key string `json:"key"`

	// NewValue ...
	NewValue string `json:"newValue"`
}

// ProtoEvent interface
func (evt DOMStorageDomStorageItemAdded) ProtoEvent() string {
	return "DOMStorage.domStorageItemAdded"
}

// DOMStorageDomStorageItemRemoved ...
type DOMStorageDomStorageItemRemoved struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`

	// Key ...
	Key string `json:"key"`
}

// ProtoEvent interface
func (evt DOMStorageDomStorageItemRemoved) ProtoEvent() string {
	return "DOMStorage.domStorageItemRemoved"
}

// DOMStorageDomStorageItemUpdated ...
type DOMStorageDomStorageItemUpdated struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`

	// Key ...
	Key string `json:"key"`

	// OldValue ...
	OldValue string `json:"oldValue"`

	// NewValue ...
	NewValue string `json:"newValue"`
}

// ProtoEvent interface
func (evt DOMStorageDomStorageItemUpdated) ProtoEvent() string {
	return "DOMStorage.domStorageItemUpdated"
}

// DOMStorageDomStorageItemsCleared ...
type DOMStorageDomStorageItemsCleared struct {

	// StorageID ...
	StorageID *DOMStorageStorageID `json:"storageId"`
}

// ProtoEvent interface
func (evt DOMStorageDomStorageItemsCleared) ProtoEvent() string {
	return "DOMStorage.domStorageItemsCleared"
}
