// generated by running "go generate" on project root

package devices

const (

	// IPhone4 type
	IPhone4 DeviceType = "iPhone 4"

	// IPhone5orSE type
	IPhone5orSE DeviceType = "iPhone 5/SE"

	// IPhone6or7or8 type
	IPhone6or7or8 DeviceType = "iPhone 6/7/8"

	// IPhone6or7or8Plus type
	IPhone6or7or8Plus DeviceType = "iPhone 6/7/8 Plus"

	// IPhoneX type
	IPhoneX DeviceType = "iPhone X"

	// BlackBerryZ30 type
	BlackBerryZ30 DeviceType = "BlackBerry Z30"

	// Nexus4 type
	Nexus4 DeviceType = "Nexus 4"

	// Nexus5 type
	Nexus5 DeviceType = "Nexus 5"

	// Nexus5X type
	Nexus5X DeviceType = "Nexus 5X"

	// Nexus6 type
	Nexus6 DeviceType = "Nexus 6"

	// Nexus6P type
	Nexus6P DeviceType = "Nexus 6P"

	// Pixel2 type
	Pixel2 DeviceType = "Pixel 2"

	// Pixel2XL type
	Pixel2XL DeviceType = "Pixel 2 XL"

	// LGOptimusL70 type
	LGOptimusL70 DeviceType = "LG Optimus L70"

	// NokiaN9 type
	NokiaN9 DeviceType = "Nokia N9"

	// NokiaLumia520 type
	NokiaLumia520 DeviceType = "Nokia Lumia 520"

	// MicrosoftLumia550 type
	MicrosoftLumia550 DeviceType = "Microsoft Lumia 550"

	// MicrosoftLumia950 type
	MicrosoftLumia950 DeviceType = "Microsoft Lumia 950"

	// GalaxySIII type
	GalaxySIII DeviceType = "Galaxy S III"

	// GalaxyS5 type
	GalaxyS5 DeviceType = "Galaxy S5"

	// JioPhone2 type
	JioPhone2 DeviceType = "JioPhone 2"

	// KindleFireHDX type
	KindleFireHDX DeviceType = "Kindle Fire HDX"

	// IPadMini type
	IPadMini DeviceType = "iPad Mini"

	// IPad type
	IPad DeviceType = "iPad"

	// IPadPro type
	IPadPro DeviceType = "iPad Pro"

	// BlackberryPlayBook type
	BlackberryPlayBook DeviceType = "Blackberry PlayBook"

	// Nexus10 type
	Nexus10 DeviceType = "Nexus 10"

	// Nexus7 type
	Nexus7 DeviceType = "Nexus 7"

	// GalaxyNote3 type
	GalaxyNote3 DeviceType = "Galaxy Note 3"

	// GalaxyNoteII type
	GalaxyNoteII DeviceType = "Galaxy Note II"

	// LaptopWithTouch type
	LaptopWithTouch DeviceType = "Laptop with touch"

	// LaptopWithHiDPIScreen type
	LaptopWithHiDPIScreen DeviceType = "Laptop with HiDPI screen"

	// LaptopWithMDPIScreen type
	LaptopWithMDPIScreen DeviceType = "Laptop with MDPI screen"

	// MotoG4 type
	MotoG4 DeviceType = "Moto G4"

	// SurfaceDuo type
	SurfaceDuo DeviceType = "Surface Duo"

	// GalaxyFold type
	GalaxyFold DeviceType = "Galaxy Fold"
)
