package main

import (
	"path/filepath"
	"regexp"

	"github.com/go-rod/rod/lib/utils"
)

func main() {
	comment := `// This file is generated by "./lib/proto/generate"`

	schema := getSchema()

	code := comment + utils.S(`

		package proto

		import "reflect"

		// Version of cdp protocol
		const Version = "v{{.major}}.{{.minor}}"
	`, "major", schema.Get("version.major").String(), "minor", schema.Get("version.minor").String())

	init := `
		var types = map[string]reflect.Type{`

	testsCode := comment + `

		package proto_test

		import (
			"testing"

			"github.com/ysmood/got"
			"github.com/go-rod/rod/lib/proto"
		)
	`

	for _, domain := range parse(schema) {
		for _, definition := range domain.definitions {
			if definition.skip {
				continue
			}

			code += definition.format()
			testsCode += definition.formatTests()

			if definition.originName != "" {
				init += utils.S(`
					"{{.name}}": reflect.TypeOf({{.type}}{}),`,
					"name", definition.domain.name+"."+definition.originName,
					"type", definition.name,
				)
			}
		}
	}

	init += `
		}
	`

	utils.E(utils.OutputFile(filepath.FromSlash("lib/proto/definitions.go"), code+init))
	utils.E(utils.OutputFile(filepath.FromSlash("lib/proto/definitions_test.go"), testsCode))

	utils.Exec("gofmt", "-s", "-w", "./lib/proto")
	utils.Exec("goimports", "-w", "./lib/proto")      // golang.org/x/tools/cmd/goimports
	utils.Exec("misspell", "-w", "-q", "./lib/proto") // github.com/client9/misspell/cmd/misspell
}

func (d *definition) comment() string {
	comment := d.description

	if comment == "" {
		comment = "..."
	}

	if d.optional {
		comment = "(optional) " + comment
	}
	if d.experimental {
		comment = "(experimental) " + comment
	}
	if d.deprecated {
		comment = "(deprecated) " + comment
	}

	comment = symbol(d.name) + " " + comment

	return regexp.MustCompile(`(?m)^`).ReplaceAllString(comment, "// ")
}

func (d *definition) format() (code string) {
	switch d.objType {
	case objTypePrimitive:
		code = utils.S(`
		{{.comment}}
		type {{.name}} {{.type}}
		`, "name", d.name, "type", d.typeName, "comment", d.comment())

		if d.enum != nil {
			code += "const ("
			for _, value := range d.enum {
				name := d.name + symbol(value)
				code += utils.S(`
				// {{.name}} enum const
				{{.name}} {{.type}} = "{{.value}}"
				`, "name", name, "type", d.name, "value", value)
			}
			code += ")\n"
		}

	case objTypeStruct:
		code = utils.S(`
		{{.comment}}
		type {{.name}} struct {
		`, "name", d.name, "comment", d.comment())

		for _, prop := range d.props {
			tag := jsonTag(prop.originName, prop.optional)

			code += utils.S(`
			{{.comment}}
			{{.name}} {{.type}} {{.tag}}
			`, "comment", prop.comment(), "name", prop.name, "type", prop.typeName, "tag", tag)
		}

		code += "}\n"

		if d.command {
			method := d.domain.name + "." + d.originName
			if d.returnValue {
				code += utils.S(`
				// MethodName of the command
				func (m {{.name}}) MethodName() string { return "{{.method}}" }

				// Call of the command, sessionID is optional.
				func (m {{.name}}) Call(caller Caller) (*{{.name}}Result, error) {
					var res {{.name}}Result
					return &res, Call(m.MethodName(), m, &res, caller)
				}
				`, "name", d.name, "method", method)
			} else {
				code += utils.S(`
				// MethodName of the command
				func (m {{.name}}) MethodName() string { return "{{.method}}" }

				// Call of the command, sessionID is optional.
				func (m {{.name}}) Call(caller Caller) error {
					return Call(m.MethodName(), m, nil, caller)
				}
				`, "name", d.name, "method", method)
			}
		}

		if d.cdpType == cdpTypeEvents {
			code += utils.S(`
				// MethodName interface
				func (evt {{.name}}) MethodName() string {
					return "{{.event}}"
				}
			`, "name", d.name, "event", d.domain.name+"."+d.originName)
		}
	}

	return
}

func (d *definition) formatTests() (code string) {
	switch d.cdpType {
	case cdpTypeCommands:
		if !d.command {
			return ""
		}

		if d.returnValue {
			return utils.S(`
				func (t C) {{.name}}() {
					c := &Client{}
					_, err := proto.{{.name}}{}.Call(&Caller{c})
					t.Nil(err)
				}
				`, "name", d.name)
		}

		return utils.S(`
			func (t C) {{.name}}() {
				c := &Client{}
				err := proto.{{.name}}{}.Call(&Caller{c})
				t.Nil(err)
			}
			`, "name", d.name)

	case cdpTypeEvents:
		return utils.S(`
		func (t C) {{.name}}() {
			e := proto.{{.name}}{}
			e.MethodName()
		}
		`, "name", d.name)
	}

	return ""
}
