// generated by running "go generate" on project root

package launcher

// DefaultRevision for chrome
// curl -s -S https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2FLAST_CHANGE\?alt\=media
const DefaultRevision = 768783
