package main

import (
	"fmt"

	"github.com/ysmood/kit"
	"github.com/ysmood/lookpath"
)

func helper() {
	lint()

	js, err := kit.ReadString(slash("lib/assets/helper.js"))
	kit.E(err)

	tpl := fmt.Sprintf(`// generated by running "go generate" on project root

package assets

// Helper for rod
var Helper = %s
`,
		"`"+encode(js)+"`",
	)

	kit.E(kit.OutputFile(slash("lib/assets/helper.go"), tpl, nil))
}

func lint() {
	defer kit.CD(slash("lib/assets"))()

	eslint, err := lookpath.LookPath(slash("node_modules/.bin"), "eslint")

	// install eslint if we don't have it
	if err != nil {
		kit.Exec("npm", "i").MustDo()
		eslint, err = lookpath.LookPath(slash("node_modules/.bin"), "eslint")
		kit.E(err)
	}

	kit.Exec(eslint, "--fix", ".").MustDo()
}
