package main

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/ysmood/kit"
)

func main() {
	dir := filepath.FromSlash("lib/js")
	path := filepath.FromSlash(dir + "/rod.js")

	kit.Exec("node_modules/.bin/eslint", "--fix", ".").Dir(dir).MustDo()

	js, err := kit.ReadString(path)
	kit.E(err)

	tpl := fmt.Sprintf(`// generated by running "go generate" on project root

package js

// Rod js
var Rod = %s
`,
		"`"+encode(js)+"`",
	)

	kit.E(kit.OutputFile(filepath.FromSlash("lib/js/js.go"), tpl, nil))
}

// not using encoding like base64 or gzip because of they will make git diff every large for small change
func encode(s string) string {
	return strings.ReplaceAll(s, "`", "` + \"`\" + `")
}
