name: Check Examples

on:
  schedule:
    - cron: '23 3 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - run: go test -run Example ./...
