name: Test Old Go
on:
  push:
    branches:
      - '**'

  pull_request:

jobs:
  test-old-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - uses: actions/checkout@v2

      # As long as the build works we don't have to run tests.
      - run: go build ./lib/examples/translator
