name: Test Windows
on:
  push:
    branches:
      - '**'

  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - run: go test -race -timeout-each=2m

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cdp-log-windows
          path: tmp/cdp-log
