name: Test Linux

on:
  push:
    branches:
      - '**'

  pull_request:

  schedule:
    - cron: '17 5 * * *'

env:
  GODEBUG: tracebackancestors=1000

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - run: go generate

      - run: go test -race -coverprofile=coverage.out ./...

      - run: go run ./lib/utils/check-cov

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cdp-log-linux
          path: |
            tmp/cdp-log
            coverage.out
